---
title: "Formateado 2"
author: "Pablo Parrilla Cañadas"
date: "2025-03-15"
output: html_document
---

```{r}
library(readxl)
library(readr)
library(dplyr)
```

Vamos a cargar todos los conjuntos de datos

```{r}
dataset=read.csv("../Datos/Iniciales/dataset_2024.csv",sep = ";")
asignaturas=read.csv("../Datos/Iniciales/asignaturas_2024.csv",sep=";")
titulaciones=read.csv("../Datos/Iniciales/titulaciones_2024.csv",sep=";")
estudiantes=read.csv("../Datos/Iniciales/estudiantes_2024_rev.csv",sep=";")
head(dataset)
```



```{r}
dataset=merge.data.frame(dataset,select(titulaciones, c("tit_hash","titnom")))

dataset=merge.data.frame(dataset,select(asignaturas,c("asi_hash","asinom")))

dataset=merge.data.frame(dataset,estudiantes)

dataset_ordenado=dataset[,c(1:3,137:143,4:136)]
head(dataset_ordenado)
```

```{r}

convertir_columnas_especificas <- function(df, columnas_a_convertir) {
  df[columnas_a_convertir] <- lapply(df[columnas_a_convertir], function(col) {
    col <- as.character(col)
    col <- trimws(col)
    col <- gsub(",", ".", col, fixed = TRUE)  
    suppressWarnings(num_col <- as.double(col))
    
    if (any(!is.na(num_col))) {
      return(num_col)
    }
    
    return(col)
  })
  return(df)
}

columnas_a_convertir <- c(13, 28, 33:55, 56, 61:68, 70:72, 73,79:143)

dataset_ordenado <- convertir_columnas_especificas(dataset_ordenado, columnas_a_convertir)
head(dataset_ordenado)
```


```{r}
dataset_ordenado=dataset_ordenado[, colSums(!is.na(dataset_ordenado) & dataset_ordenado != "") > 0, drop = FALSE]
dataset_ordenado$fecha_datos <- as.POSIXct(dataset_ordenado$fecha_datos, format="%Y-%m-%d %H:%M:%S")
dataset_ordenado$baja_fecha=as.POSIXct(dataset_ordenado$baja_fecha, format="%Y-%m-%d")
```

```{r}
#estudiantes=select(dataset_ordenado,c(1:12,15:26,30:31,55:56,58))
poliformat=select(dataset_ordenado,c(1:5,79:137))
head(poliformat)
```



```{r}
filtrar_columnas_por_palabra <- function(df, palabra) {
  columnas_filtradas=grep(palabra, names(df), value = TRUE, ignore.case = TRUE)
  
  df_filtrado=df[, columnas_filtradas, drop = FALSE]
  
  return(df_filtrado)
}

#a=dataset_ordenado

eventos=filtrar_columnas_por_palabra(poliformat, "pft_events")
logged=filtrar_columnas_por_palabra(poliformat, "logged")
visits=filtrar_columnas_por_palabra(poliformat, "visits")
minutes=filtrar_columnas_por_palabra(poliformat, "minutes")
wifi=filtrar_columnas_por_palabra(poliformat, "wifi")
resource_events=filtrar_columnas_por_palabra(poliformat, "resource_events")
resource_days=filtrar_columnas_por_palabra(poliformat, "resource_days")
assignment=filtrar_columnas_por_palabra(poliformat, "assignment")
test=filtrar_columnas_por_palabra(poliformat, "test")

#Con las columnas finales ordenadas, todo será más sencillo
dataset_ordenado=dataset_ordenado[,1:78]
dataset_ordenado=cbind(dataset_ordenado,eventos,logged,visits,minutes,wifi,resource_days,resource_events,assignment,test)

#Formateamos a 0 para poder mostrar gráficas
dataset_ordenado[,79:137 ] <- replace(dataset_ordenado[,79:137 ], is.na(dataset_ordenado[,79:137 ]), 0)
```


```{r}
fecha_mas_frecuente=dataset_ordenado %>%
  filter(!is.na(baja_fecha)) %>%
  group_by(dni_hash, baja_fecha) %>%
  summarise(n = n(), .groups = "drop") %>%
  group_by(dni_hash) %>%
  slice_max(order_by = n, n = 1, with_ties = FALSE) %>%
  rename(fecha_mas_frecuente = baja_fecha)

conteo_abandonos=dataset_ordenado %>%
  group_by(dni_hash) %>%
  summarise(asi_left = sum(!is.na(baja_fecha)), abandono = ifelse(asi_left > 5, 1, 0), .groups = "drop")

abandono=dataset_ordenado %>%
  distinct(dni_hash, .keep_all = FALSE) %>%  
  left_join(conteo_abandonos, by = "dni_hash") %>%
  left_join(fecha_mas_frecuente, by = "dni_hash")

```

```{r}
dataset_ordenado$evento_poliformat_asg=rowSums(dataset_ordenado[,79:85])
dataset_ordenado$loggins_asg=rowSums(dataset_ordenado[,86:92])
dataset_ordenado$visitas_asg=rowSums(dataset_ordenado[,93:99])
dataset_ordenado$minutos_asg=rowSums(dataset_ordenado[,100:106])
dataset_ordenado$n_res_day_asg=rowSums(dataset_ordenado[,114:120])
dataset_ordenado$n_res_events_asg=rowSums(dataset_ordenado[,121:127])
dataset_ordenado$asign_asg=rowSums(dataset_ordenado[,128:132])
dataset_ordenado$test_asg=rowSums(dataset_ordenado[,132:137])
colnames(dataset_ordenado)
```

```{r}
columnas_a_sumar=colnames(dataset_ordenado[,c(79:106,114:137)])

dataset_ordenado=dataset_ordenado %>%
  group_by(dni_hash) %>%
  mutate(across(all_of(columnas_a_sumar), ~ sum(.x, na.rm = TRUE), .names = "{.col}_est")) %>%
  ungroup()
```

Ahora vamos a intentar quitar las asignaturas que sabemos que son de segundo cuatrimestre en función se su actividad en poliformat.

```{r warning=FALSE}

grupo_asg=dataset_ordenado %>%
  group_by(asi_hash, tit_hash) %>%
  summarise(across(c(79:104, 114:137), sum, na.rm = TRUE))


asg_1_cuatri=grupo_asg %>%
  filter(rowSums(across(where(is.numeric) & !any_of(c("asi_hash", "tit_hash")))) > 0)

filtrado=dataset_ordenado %>%
  semi_join(grupo_asg, by = c("asi_hash", "tit_hash"))

```

Vale, aquí vamos a separar en varios dataset y según necesitemos vamos concatenando, porque si no, esto es un desastre.


```{r}
#tabla <- as.data.frame(table(df))
#tabla <- tabla[order(-tabla$Freq), ]

columnas_utiles=c(
  "dni_hash", "asi_hash", "tit_hash", "titnom", "asinom", "nacionalitat",
  "data_nac", "sexe", "alta_universitat", "prov_origen", "anyo_ingreso", "tipo_ingreso",
  "nota10", "nota14", "campus", "estudios_p", "estudios_m", "dedicacion",
  "desplazado", "discapacidad", "becado", "preferencia_seleccion", "baja_fecha", "caca",
  "grupos_por_tipocredito", "matricula_activa", "nota_asig", "fecha_datos", "cod_centro",
  "curso_mas_bajo", "curso_mas_alto", "cred_mat1", "cred_mat2", "cred_mat3", "cred_mat4",
  "cred_mat5", "cred_mat6", "cred_sup_normal", "cred_sup_espec", "cred_sup",
  "cred_mat_normal", "cred_mat_movilidad", "cred_ptes_acta", "cred_mat_practicas",
  "cred_mat_sem_a", "cred_mat_sem_b", "cred_mat_anu", "cred_mat_total",
  "cred_sup_sem_a", "cred_sup_sem_b", "cred_sup_anu", "cred_sup_total",
  "rendimiento_cuat_a", "rendimiento_total", "exento_npp", "anyo_inicio_estudios",
  "es_retitulado", "es_adaptado", "cred_sup_1o", "cred_sup_2o", "cred_sup_3o",
  "cred_sup_4o", "cred_sup_5o", "cred_sup_6o", "practicas", "actividades", "ajuste",
  "cred_sup_tit", "cred_pend_sup_tit", "impagado_curso_mat", "asig1", "pract1", "activ1",
  "total1", "ajuste1", "rend_total_ultimo", "rend_total_penultimo", "rend_total_antepenultimo",
  "pft_events_2024_7", "pft_events_2024_8", "pft_events_2024_9", "pft_events_2024_10",
  "pft_events_2024_11", "pft_events_2024_12", "pft_events_2025_1", "pft_days_logged_2024_7",
  "pft_days_logged_2024_8", "pft_days_logged_2024_9", "pft_days_logged_2024_10",
  "pft_days_logged_2024_11", "pft_days_logged_2024_12", "pft_days_logged_2025_1",
  "pft_visits_2024_7", "pft_visits_2024_8", "pft_visits_2024_9", "pft_visits_2024_10",
  "pft_visits_2024_11", "pft_visits_2024_12", "pft_visits_2025_1", "pft_total_minutes_2024_7",
  "pft_total_minutes_2024_8", "pft_total_minutes_2024_9", "pft_total_minutes_2024_10",
  "pft_total_minutes_2024_11", "pft_total_minutes_2024_12", "pft_total_minutes_2025_1",
  "n_wifi_days_2024_7", "n_wifi_days_2024_8", "n_wifi_days_2024_9", "n_wifi_days_2024_10",
  "n_wifi_days_2024_11", "n_wifi_days_2024_12", "n_wifi_days_2025_1",
  "n_resource_days_2024_7", "n_resource_days_2024_8", "n_resource_days_2024_9",
  "n_resource_days_2024_10", "n_resource_days_2024_11", "n_resource_days_2024_12",
  "n_resource_days_2025_1", "resource_events_2024_7", "resource_events_2024_8",
  "resource_events_2024_9", "resource_events_2024_10", "resource_events_2024_11",
  "resource_events_2024_12", "resource_events_2025_1", "pft_assignment_submissions_2024_9",
  "pft_assignment_submissions_2024_10", "pft_assignment_submissions_2024_11",
  "pft_assignment_submissions_2024_12", "pft_assignment_submissions_2025_1",
  "pft_test_submissions_2024_9", "pft_test_submissions_2024_10", "pft_test_submissions_2024_11",
  "pft_test_submissions_2024_12", "pft_test_submissions_2025_1", "evento_poliformat_asg",
  "loggins_asg", "visitas_asg", "minutos_asg", "n_res_day_asg", "n_res_events_asg",
  "asign_asg", "test_asg", "pft_events_2024_7_est", "pft_events_2024_8_est",
  "pft_events_2024_9_est", "pft_events_2024_10_est", "pft_events_2024_11_est",
  "pft_events_2024_12_est", "pft_events_2025_1_est", "pft_days_logged_2024_7_est",
  "pft_days_logged_2024_8_est", "pft_days_logged_2024_9_est", "pft_days_logged_2024_10_est",
  "pft_days_logged_2024_11_est", "pft_days_logged_2024_12_est", "pft_days_logged_2025_1_est",
  "pft_visits_2024_7_est", "pft_visits_2024_8_est", "pft_visits_2024_9_est",
  "pft_visits_2024_10_est", "pft_visits_2024_11_est", "pft_visits_2024_12_est",
  "pft_visits_2025_1_est", "pft_total_minutes_2024_7_est", "pft_total_minutes_2024_8_est",
  "pft_total_minutes_2024_9_est", "pft_total_minutes_2024_10_est",
  "pft_total_minutes_2024_11_est", "pft_total_minutes_2024_12_est", "pft_total_minutes_2025_1_est",
  "n_resource_days_2024_7_est", "n_resource_days_2024_8_est", "n_resource_days_2024_9_est",
  "n_resource_days_2024_10_est", "n_resource_days_2024_11_est", "n_resource_days_2024_12_est",
  "n_resource_days_2025_1_est", "resource_events_2024_7_est", "resource_events_2024_8_est",
  "resource_events_2024_9_est", "resource_events_2024_10_est", "resource_events_2024_11_est",
  "resource_events_2024_12_est", "resource_events_2025_1_est", "pft_assignment_submissions_2024_9_est",
  "pft_assignment_submissions_2024_10_est", "pft_assignment_submissions_2024_11_est",
  "pft_assignment_submissions_2024_12_est", "pft_assignment_submissions_2025_1_est",
  "pft_test_submissions_2024_9_est", "pft_test_submissions_2024_10_est",
  "pft_test_submissions_2024_11_est", "pft_test_submissions_2024_12_est",
  "pft_test_submissions_2025_1_est")

asignaturas=filtrado[,c("asi_hash", "tit_hash","titnom", "asinom","evento_poliformat_asg",
  "loggins_asg", "visitas_asg", "minutos_asg", "n_res_day_asg", "n_res_events_asg",
  "asign_asg", "test_asg")]

demografía=filtrado[,c("dni_hash","tit_hash", "titnom","nacionalitat",
  "data_nac", "sexe", "alta_universitat", "prov_origen", "anyo_ingreso", "tipo_ingreso",
  "nota10", "nota14", "campus", "estudios_p", "estudios_m", "dedicacion",
  "desplazado", "discapacidad", "becado", "preferencia_seleccion","n_wifi_days_2024_7", "n_wifi_days_2024_8", "n_wifi_days_2024_9", "n_wifi_days_2024_10",
  "n_wifi_days_2024_11", "n_wifi_days_2024_12", "n_wifi_days_2025_1")]

creditos=filtrado[,c( "dni_hash","tit_hash", "titnom","cred_mat1", "cred_mat2", "cred_mat3", "cred_mat4","cred_mat5", "cred_mat6", "cred_sup_normal", "cred_sup_espec", "cred_sup",
  "cred_mat_normal", "cred_mat_movilidad", "cred_ptes_acta", "cred_mat_practicas",
  "cred_mat_sem_a", "cred_mat_sem_b", "cred_mat_anu", "cred_mat_total",
  "cred_sup_sem_a", "cred_sup_sem_b", "cred_sup_anu", "cred_sup_total",
  "rendimiento_cuat_a", "rendimiento_total", "exento_npp", "anyo_inicio_estudios",
  "es_retitulado", "es_adaptado", "cred_sup_1o", "cred_sup_2o", "cred_sup_3o",
  "cred_sup_4o", "cred_sup_5o", "cred_sup_6o", "practicas", "actividades", "ajuste",
  "cred_sup_tit", "cred_pend_sup_tit", "impagado_curso_mat", "asig1", "pract1", "activ1",
  "total1", "ajuste1", "rend_total_ultimo", "rend_total_penultimo", "rend_total_antepenultimo")]

poliformat=filtrado[,c("dni_hash", "tit_hash", "titnom","pft_events_2024_7_est", "pft_events_2024_8_est",
  "pft_events_2024_9_est", "pft_events_2024_10_est", "pft_events_2024_11_est",
  "pft_events_2024_12_est", "pft_events_2025_1_est", "pft_days_logged_2024_7_est",
  "pft_days_logged_2024_8_est", "pft_days_logged_2024_9_est", "pft_days_logged_2024_10_est",
  "pft_days_logged_2024_11_est", "pft_days_logged_2024_12_est", "pft_days_logged_2025_1_est",
  "pft_visits_2024_7_est", "pft_visits_2024_8_est", "pft_visits_2024_9_est",
  "pft_visits_2024_10_est", "pft_visits_2024_11_est", "pft_visits_2024_12_est",
  "pft_visits_2025_1_est", "pft_total_minutes_2024_7_est", "pft_total_minutes_2024_8_est",
  "pft_total_minutes_2024_9_est", "pft_total_minutes_2024_10_est",
  "pft_total_minutes_2024_11_est", "pft_total_minutes_2024_12_est", "pft_total_minutes_2025_1_est",
  "n_resource_days_2024_7_est", "n_resource_days_2024_8_est", "n_resource_days_2024_9_est",
  "n_resource_days_2024_10_est", "n_resource_days_2024_11_est", "n_resource_days_2024_12_est",
  "n_resource_days_2025_1_est", "resource_events_2024_7_est", "resource_events_2024_8_est",
  "resource_events_2024_9_est", "resource_events_2024_10_est", "resource_events_2024_11_est",
  "resource_events_2024_12_est", "resource_events_2025_1_est", "pft_assignment_submissions_2024_9_est",
  "pft_assignment_submissions_2024_10_est", "pft_assignment_submissions_2024_11_est",
  "pft_assignment_submissions_2024_12_est", "pft_assignment_submissions_2025_1_est",
  "pft_test_submissions_2024_9_est", "pft_test_submissions_2024_10_est",
  "pft_test_submissions_2024_11_est", "pft_test_submissions_2024_12_est",
  "pft_test_submissions_2025_1_est")]

poliformat= poliformat %>% 
   left_join(select(abandono, dni_hash, abandono), by = "dni_hash")

demografía=demografía %>%
  distinct(dni_hash, .keep_all = TRUE) %>% 
   left_join(select(abandono, dni_hash, abandono), by = "dni_hash")

creditos=creditos %>%
  distinct(dni_hash, .keep_all = TRUE) %>% 
   left_join(select(abandono, dni_hash, abandono), by = "dni_hash")

asignaturas=asignaturas %>%
  distinct(asi_hash, .keep_all = TRUE)

head(poliformat)

```

Vamos a salvar las variables que nos interesan.

```{r}
save(abandono,asignaturas, creditos, demografía, poliformat,file="../Datos/Segundo_intento/Datasets.RData")
```

